name: "action-coolify"
description: "Trigger Coolify Deployments (and wait for them to finish)"
inputs:
  coolify-url: 
    description: "Coolify API URL"
    required: false
    default: "https://app.coolify.io"
  api-key:
    description: "Coolify API key"
    required: true
  wait:
    description: "Seconds to wait for the deployment to finish"
    required: false
    default: "600"
  tag:
    description: "Tag name(s). Comma separated list is also accepted."
    required: false
  uuid:
    description: "Resource UUID(s). Comma separated list is also accepted."
    required: false
  force:
    description: "Force rebuild (without cache)"
    required: false
    default: "false"

runs:
  using: "node20"
  main: dist/action.js
